# Generated by Django 3.2.7 on 2022-01-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandwichapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sandwich',
            name='price',
        ),
        migrations.AlterField(
            model_name='bread',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='cheese',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sauce',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
