# Generated by Django 3.2.7 on 2022-01-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandwichapp', '0002_auto_20220129_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandwich',
            name='price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
